### ISSUE TITLE
Setup separate environments in AWS

### ISSUE THREAD

**Issue by owenwe** [owenwe/cdsWebserver#6]
dev.edexchange.org/net
http://ec2-52-26-231-231.us-west-2.compute.amazonaws.com:8080/home

test.edexchange.org/net
pilot.edexchange.org/net
prod.edexchange.org/net

**Comment by chessracer** [comment]
Currently there are QA and Pilot environments in AWS. Note that we have a certificate for ccctechcenter.org, hence domain names used. I'm unsure of the availability of edexchange.org, or if that is even a requirement, or just an initial suggestion.
https://edex-directory-qa.ccctechcenter.org:8443/home
https://edex-directory-pilot.ccctechcenter.org:8443/home

**Comment by jhwhetstone** [comment]
AWS has been setup for both QA and PILOT environments.
